
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/api/posts/**
        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/comments/**
        - id: react-service
          uri: lb://react-service
          predicates:
            - Path=/reactions/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

#app:
#  eureka-server: eureka-server-container-2.0

server:
  port: 8022
